export const PAGINATION_DEFAULTS = {
  PAGE: 1,
  LIMIT: 10,
  MAX_LIMIT: 100,
};

export const TRANSACTION_LIMITS = {
  DAILY_WITHDRAWAL: 5000,
  DAILY_TRANSFER: 50000,
  SINGLE_TRANSACTION: 25000,
};

export const ACCOUNT_DEFAULTS = {
  INITIAL_BALANCE: 0,
  OVERDRAFT_LIMIT: 0,
};

export const INTEREST_RATES = {
  SAVINGS: 2.5,
  CHECKING: 0.1,
  PERSONAL_LOAN: 5.5,
  MORTGAGE: 3.2,
  AUTO_LOAN: 4.0,
  STUDENT_LOAN: 3.8,
  BUSINESS_LOAN: 6.0,
};
